### ISSUE TITLE
Unable to display RTSP stream

### ISSUE THREAD

**Issue by Kaynelua** [sahilparekh/GStreamer-Python#3]
Hi sahil,

Appreciate the work you have put in to read a rtsp stream using gstreamer.
I am trying to read from a Mambo Parrot drone a rtsp stream as numpy arrays. I have ran your instructions and code accordingly. The window pops up but after 1-2 frames it just stops and breaks.

The following error was thrown up :
Error received from element m_rtspsrc: gst-resource-error-quark: Could not read from resource. (9)
Debugging information: gstrtspsrc.c(4662): gst_rtspsrc_loop_interleaved (): /GstPipeline:pipeline0/GstRTSPSrc:m_rtspsrc:
Could not receive message. (Parse error)

This error also keeps popping up before the above error:
Unexpected message received
Unexpected message received

Hope you can point me in the right direction as to how to fix this. Thank you very much!

**Comment by sahilparekh** [comment]
Hi @Kaynelua ,

Thanks for pointing it out.
"Unexpected message received" may pop up sometimes because of network conditioning.
To handle this i have updated the code to shutdown the stream if error exceeds the predefined allowed max error counts.
This will give you a chance in main program to try to re-initialize the stream on stopbit untill you find stable connection again.
 Let me know if that helped you.

**Comment by sahilparekh** [comment]
@Kaynelua Please let me know if this helped you?

**Comment by Kaynelua** [comment]
Sure I will keep you updated once I tried it

**Comment by Kaynelua** [comment]
Sorry for the late update i was really tied up with reports. Anyway, this didnt fix the problem, and i got the same exact error message. Running Gstreamer directly on command line worked for me :

gst-launch-1.0 rtspsrc location=rtsp://192.168.99.1/media/stream2 latency=10 ! decodebin ! autovideosink
 
But cant seem to make it work on python i have no idea why
